In [1]:
import numpy as np

In [18]:
arr1 = np.array([1, 2, 3, 4, 5])

print(type(arr1))
print(f"arr[1] = {arr1[1]}") 
arr1

<class 'numpy.ndarray'>
arr[1] = 2


array([1, 2, 3, 4, 5])

In [8]:
# multi dimensional array

arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(f"shape: {arr2.shape}")
print(f"dimentionality: {arr2.ndim}")
arr2

shape: (2, 2, 3)
dimentionality: 3


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
# make array higher  dimentional
arr3 = np.array([1, 2, 3, 4], ndmin=5)

print(arr3)
print('number of dimensions :', arr3.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [17]:
# acces higher dimentional array

arr4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('last element on 2nd row: ', arr4[1, -1])
print('last element on 2nd row: ', arr4[1][-1])

last element on 2nd row:  10
last element on 2nd row:  10


In [23]:
# array slicing
print(arr1)
print(arr1[1:3])
print(arr1[1:])

[1 2 3 4 5]
[2 3]
[2 3 4 5]


In [30]:
# ranges
arr5 = np.array(range(30))
print(arr5)
print(arr5[2::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [32]:
# other data types

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)
arr

<U6


array(['apple', 'banana', 'cherry'], dtype='<U6')

In [41]:
# types

np.array([1, 2, 3, 4], dtype='i')  # ints

array([1, 2, 3, 4], dtype=int32)

In [47]:
# type casting
arr6 = np.array([1.1, 2.1, 3.1])

newarr = arr6.astype('i')
newarr2 = arr6.astype(int)

print(arr6.dtype)
print()
print(newarr)
print(newarr.dtype)
print()
print(newarr2)
print(newarr2.dtype)

float64

[1 2 3]
int32

[1 2 3]
int64


In [50]:
# matrix multiplication
arr7 = np.array([[1, 2], [3, 4]])
arr8 = np.array([[5, 6], [7, 8]])

mult = np.matmul(arr7, arr8)
print(mult)
print(mult.shape)

[[19 22]
 [43 50]]
(2, 2)
